services:
  db: # host computer yani windows se docker ka bahr software se connect krny k liye host men locahost likhen
    image: postgres:17-alpine # pgsql 18 has no image on docker hub now until dec 2026
    container_name: gql-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gql_core
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: